### ISSUE TITLE
Do we still need DOIs for the presentations?

### ISSUE THREAD

**Issue by bernhold** [bssw-tutorial/tutorial-management#37]
Historically, we've deposited the presentations for (nearly) all of our tutorials on FigShare and used DOIs to refer to them.  One reason for that was to ensure long-term accessibility of the material.  Another was to facilitate citation of the material.  And an underlying reason was because we didn't have a particularly good place within the project to host the O(10) presentations associated with each tutorial event.

Now...

* We have a web site dedicated to the tutorial and could easily host the presentations there.  Hosting on github, we can expect it to be fairly long-lived.
* That doesn't provide a DOI, of course. *If* we decide we really need on, we could use GitHub's release mechanism and hook it up to Zenodo (I think you can do the same with FigShare).  I'm already making GH releases of the presentations repository for each event.  It would just be a matter of connecting to Zenodo/FigShare.
  - This *should* simplify the process of getting a DOI, since I think we would establish a single record and push releases to it, rather than our current practice which requires setting up a separate and complete record for each event.
  - Even though the result is not quite as "pretty" (or informative) as having a separate FigShare entry for each event, it should still suffice if someone wants to cite it or access it in the far future.

P.S.  Has anyone ever actually cited a BSSw tutorial using our requested citation?  I couldn't find any evidence of it on Google.

**Comment by bernhold** [comment]
The more I think about this, the stronger my feeling that we don't really need DOIs for the presentations -- we have been using FigShare as much as a simple hosting site as an archival repository.  Now we have our own site.  There should be no problems hosting our own presentations.  It would significantly simplify the overall workflow.

If we host presentations on the web site, we *should* have some kind of versioning mechanism for the presentations there, so that participants can figure out whether there are updates since they last downloaded.

**Comment by pagrubel** [comment]
I agree that it isn't necessary to have DOI's for presentations

**Comment by rinkug** [comment]
I agree having our own site is enough. Having a DOI is nice, but we can refer to our own site.

**Comment by jarrah42** [comment]
I'm fine with using GH links for now.

**Comment by frobnitzem** [comment]
I haven't seen presentation citations either - which leads to a preference for the simplest mechanism.

Note, however, that when I've used zenodo it makes a copy of the entire repo's release.  If you want to release only the pdf files, that could involve creating a separate "release-only" repo.

**Comment by bernhold** [comment]
Yeah, I'd considered trying to use the GitHub-Zenodo (and similar things are possible with FigShare) automation, but they don't really fit our use case, in several dimensions.

I have, however, been making GH "releases" in the presentations repo for each tutorial (since 2021).  They're manual, but the tutorial website's "utility" pages generate the commands required, so they're easy to do.  The files in those releases are the zips of the presentation PDFs.  That's probably what we'd link to.  Alternatively, we can add a copy of the zip to the tutorial website itself so that it is self-contained.

**Comment by jwillenbring** [comment]
I think the DOIs are nice, but if it simplifies the workflow, the small benefit is not worth the extra cost.

**Comment by bernhold** [comment]
The consensus seems to be that we don't really need the DOIs.  I need to update the website logic so that it understands presentations that have regular URLs instead of DOIs.

**Comment by bernhold** [comment]
Created 
* https://github.com/bssw-tutorial/tutorial-management/issues/85
* https://github.com/bssw-tutorial/bssw-tutorial.github.io/issues/77
as successors to this issue.
